channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.2.1
- pip:
  - mlflow==2.20.1
  - cloudpickle==2.2.1
  - numpy==1.22.2
  - psutil==6.1.1
  - scikit-learn==1.2.0
  - scipy==1.11.1
name: mlflow-env
